### PR TITLE
use faker to generate random valid Texas ZIP code

### LINKED ISSUE #2: Non-Texas ZIP codes being returned
The data being returned for `text-4` rarely is a valid Texas zip code, The current sample return in the readme is just such a case.

### PR DESCRIPTION
**Pull request by coolgeek6667**
Resolves #2 

* Use faker to generate random Texas ZIP code
* Clean up unused data

### CODE REVIEW

**Review by dcbark01 — APPROVED** [review]
Nice PR. Extra points for catching the incorrect zip code in the README file also :+1:

**Review by dcbark01 — APPROVED** [review]

**Review by dcbark01 — APPROVED** [review]
Approved.

**Comment by coolgeek6667** [comment]
whoops, accidentally deleted by branch before it was merged

**Comment by andria-dev** [comment]
Nice, much more succinct. Merging now.

**Pull request merged**
